FROM konvergence/duplicity:3.0.7

ARG MYSQL_VERSION

RUN [ -n "${MYSQL_VERSION}" ]

# Image Label
LABEL maintainer="konvergence.com" \
      website="https://www.konvergence.com" \
      description="volume backup with duplicity using openstack swift, sftp or filesystem volume" \
      release="${RELEASE}"

RUN echo "#### install mysql-client" \
    && apt-get update \
    && apt-get install -y mysql-client-${MYSQL_VERSION} \
&& echo "#### clean " \
     && apt-get clean \
     && rm -rf /var/lib/apt/lists/* \
     && rm -rf /tmp/*
