FROM konvergence/duplicity:3.0.3.2-r1

ARG PG_VERSION

RUN [ -n "${PG_VERSION}" ]

# Image Label
LABEL maintainer="konvergence.com" \
      website="https://www.konvergence.com" \
      description="volume backup with duplicity using openstack swift, sftp or filesystem volume" \
      release="${RELEASE}"

RUN echo "#### install postgresql-client" \
    && apt-get update \
    && apt-get install -y ca-certificates gnupg wget \
    && echo "deb http://apt.postgresql.org/pub/repos/apt focal-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
    && (wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg >/dev/null) \  
    && apt-get update \
    && apt-get install -y  postgresql-client-${PG_VERSION} \
&& echo "#### clean " \
     && apt-get clean \
     && rm -rf /var/lib/apt/lists/* \
     && rm -rf /tmp/*
